/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Returns ``{"status": "ok"}`` when the app is up.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload
         * @description Upload stage: land a ZIP into a fresh run workspace and detect the root.
         */
        post: operations["upload_api_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Github
         * @description Upload stage: shallow-clone a public GitHub repo into a fresh run.
         */
        post: operations["upload_github_api_upload_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse
         * @description Parse stage: run the Node worker and return the Knowledge Graph JSON.
         */
        post: operations["parse_api_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Analysis stage: parse the project, then analyze migratability.
         */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan
         * @description Plan stage: parse + analyze + plan; returns the report and plan together.
         */
        post: operations["plan_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Migrate
         * @description Migrate stage: emit the RN project, validate it, and map diagnostics.
         *
         *     For a ``runId`` the RN project is emitted into that run's ``output/`` dir, so
         *     ``GET /api/runs/{runId}/download`` can package it afterwards.
         */
        post: operations["migrate_api_migrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download
         * @description Download stage: stream the emitted React Native project back as a ZIP.
         */
        get: operations["download_api_runs__run_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisReport */
        AnalysisReport: {
            /** Projectname */
            projectName: string;
            summary: components["schemas"]["Summary"];
            /** Libraries */
            libraries?: components["schemas"]["LibraryFinding"][];
            /** Components */
            components?: components["schemas"]["ComponentFinding"][];
            routing: components["schemas"]["RoutingReport"];
            styling: components["schemas"]["StylingReport"];
            /** Domains */
            domains?: components["schemas"]["DomainRisk"][];
            /** Blockers */
            blockers?: components["schemas"]["Issue"][];
            /** Warnings */
            warnings?: components["schemas"]["Issue"][];
            /** Coverage */
            coverage: number;
            /** Confidence */
            confidence: number;
            /**
             * Risk
             * @enum {string}
             */
            risk: "low" | "medium" | "high";
            /** Contributions */
            contributions?: components["schemas"]["ScoreContribution"][];
        };
        /** ApiClient */
        ApiClient: {
            /** Id */
            id: string;
            /**
             * Library
             * @enum {string}
             */
            library: "axios" | "fetch";
            /** File */
            file: string;
            /** Baseurl */
            baseURL?: string | null;
        };
        /** ApiLayer */
        ApiLayer: {
            /** Clients */
            clients?: components["schemas"]["ApiClient"][];
            /** Endpoints */
            endpoints?: components["schemas"]["Endpoint"][];
        };
        /** Asset */
        Asset: {
            /** Path */
            path: string;
            /** Type */
            type: string;
            /** Referencedby */
            referencedBy?: string[];
        };
        /** Body_upload_api_upload_post */
        Body_upload_api_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * CandidateRoot
         * @description A directory in the landed tree that looks like a React project root.
         *
         *     ``path`` is relative to :attr:`IngestedProject.rootPath` (``"."`` when the
         *     project sits at the top of the extract). ``reactVersion`` is the version
         *     range declared for ``react`` in that ``package.json`` — the signal that
         *     makes this a React project and not just any Node package.
         */
        CandidateRoot: {
            /** Path */
            path: string;
            /** Packagename */
            packageName: string;
            /** Reactversion */
            reactVersion: string;
        };
        /** Component */
        Component: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** File */
            file: string;
            /**
             * Exporttype
             * @enum {string}
             */
            exportType: "default" | "named";
            /** Props */
            props?: components["schemas"]["PropInfo"][];
            /** Propsextends */
            propsExtends?: string[];
            /** Hooksused */
            hooksUsed?: string[];
            /** Childcomponents */
            childComponents?: string[];
            /** Jsxelements */
            jsxElements?: {
                [key: string]: number;
            };
            /** Eventhandlers */
            eventHandlers?: string[];
            /** Stylingapproach */
            stylingApproach?: ("tailwind" | "css-module" | "inline" | "none")[];
            /** Tailwindclasses */
            tailwindClasses?: string[];
            /** Cssmoduleimports */
            cssModuleImports?: string[];
            /** Webapis */
            webApis?: string[];
            /** Textnodes */
            textNodes?: components["schemas"]["TextNodeInfo"][];
            /** Layouthints */
            layoutHints?: components["schemas"]["LayoutHint"][];
            /** Images */
            images?: components["schemas"]["ImageInfo"][];
            /** Inlinestyles */
            inlineStyles?: components["schemas"]["InlineStyleInfo"][];
        };
        /** ComponentFinding */
        ComponentFinding: {
            /** Componentid */
            componentId: string;
            /** Name */
            name: string;
            /** File */
            file: string;
            /**
             * Difficulty
             * @enum {string}
             */
            difficulty: "trivial" | "easy" | "medium" | "hard" | "blocked";
            /** Score */
            score: number;
            /** Issues */
            issues?: components["schemas"]["Issue"][];
        };
        /**
         * ConfidenceSource
         * @description Provenance of a migrated unit — Confidence is COMPUTED from this, never
         *     estimated. The AI values are reserved so the AI Resolution Engine plugs in
         *     without schema churn.
         * @enum {string}
         */
        ConfidenceSource: "deterministic" | "deterministic-warning" | "ai-validated" | "ai-failed" | "unhandled";
        /**
         * Diagnostic
         * @description One structured tool diagnostic — parsed, never a raw text blob.
         */
        Diagnostic: {
            /**
             * Source
             * @enum {string}
             */
            source: "typecheck" | "bundle" | "lint";
            /** File */
            file?: string | null;
            /** Line */
            line?: number | null;
            /** Column */
            column?: number | null;
            /** Code */
            code?: string | null;
            /**
             * Severity
             * @default error
             * @enum {string}
             */
            severity: "error" | "warning";
            /** Message */
            message: string;
        };
        /**
         * DomainRisk
         * @description A functional domain detected in the project (evidence-based, from KG
         *     facts only — a domain with no signal is simply absent, never "unknown").
         */
        DomainRisk: {
            /** Domain */
            domain: string;
            /**
             * Risk
             * @enum {string}
             */
            risk: "low" | "medium" | "high";
            /** Reason */
            reason: string;
            /** Rnnotes */
            rnNotes: string;
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
        };
        /** Edge */
        Edge: {
            /** From */
            from: string;
            /** To */
            to: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "renders" | "imports" | "uses-hook" | "uses-store" | "calls-api";
        };
        /**
         * EmittedFile
         * @description One file written into the React Native output tree.
         *
         *     ``provenance`` is derived from what actually happened to the file:
         *
         *     - ``deterministic``          — transformed by rules, no warnings, no residue.
         *     - ``deterministic-warning``  — transformed by rules but flagged (warnings)
         *       and/or generated (scaffold, navigator).
         *     - ``unhandled``              — carries ``unhandled`` residue that only the AI
         *       Resolution Engine can resolve; excluded from Confidence.
         */
        EmittedFile: {
            /** Path */
            path: string;
            /** Sourcefile */
            sourceFile?: string | null;
            provenance: components["schemas"]["ConfidenceSource"];
            /** Warnings */
            warnings?: components["schemas"]["TransformWarning"][];
            /** Unhandled */
            unhandled?: components["schemas"]["UnhandledItem"][];
            /** Todocodes */
            todoCodes?: string[];
        };
        /**
         * EmittedProject
         * @description The assembled React Native project + per-file provenance.
         */
        EmittedProject: {
            /** Outdir */
            outDir: string;
            /** Files */
            files?: components["schemas"]["EmittedFile"][];
            /** Skipped */
            skipped?: components["schemas"]["SkippedFile"][];
            /**
             * Todocount
             * @default 0
             */
            todoCount: number;
        };
        /** Endpoint */
        Endpoint: {
            /** Method */
            method?: string | null;
            /** Url */
            url?: string | null;
            /** File */
            file: string;
        };
        /**
         * Evidence
         * @description The KG fact that triggered an issue.
         */
        Evidence: {
            /** File */
            file?: string | null;
            /** Detail */
            detail: string;
        };
        /** FileNode */
        FileNode: {
            /** Path */
            path: string;
            /**
             * Type
             * @enum {string}
             */
            type: "component" | "hook" | "store" | "api" | "style" | "config" | "asset" | "other";
            /** Loc */
            loc: number;
        };
        /** GithubUploadRequest */
        GithubUploadRequest: {
            /**
             * Url
             * @description Public GitHub repo URL.
             */
            url: string;
            /**
             * Ref
             * @description Optional branch/tag to clone.
             */
            ref?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response schema for the health check endpoint.
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** Hook */
        Hook: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** File */
            file: string;
            /** Iscustom */
            isCustom: boolean;
            /** Usedby */
            usedBy?: string[];
        };
        /**
         * ImageInfo
         * @description Info about one ``<img>``.
         */
        ImageInfo: {
            /** Hasexplicitsize */
            hasExplicitSize: boolean;
            /**
             * Srckind
             * @enum {string}
             */
            srcKind: "import" | "literal" | "dynamic";
            /** Src */
            src?: string | null;
        };
        /**
         * IngestedProject
         * @description The result of landing an upload into a run workspace.
         *
         *     ``detectedRoot`` is the absolute path the rest of the pipeline should treat
         *     as the project root; ``candidateRoots`` lists every React project found so
         *     the caller can override the choice in a monorepo with more than one app.
         */
        IngestedProject: {
            /** Runid */
            runId: string;
            /** Rootpath */
            rootPath: string;
            /**
             * Source
             * @enum {string}
             */
            source: "zip" | "github";
            /** Detectedroot */
            detectedRoot: string;
            /** Candidateroots */
            candidateRoots?: components["schemas"]["CandidateRoot"][];
            /** Filecount */
            fileCount: number;
            /** Sizebytes */
            sizeBytes: number;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * InlineStyleInfo
         * @description An element carrying an inline ``style={{…}}`` object.
         */
        InlineStyleInfo: {
            /** Elementtag */
            elementTag: string;
            /** Properties */
            properties?: string[];
        };
        /**
         * Issue
         * @description A single finding, always tied to evidence.
         */
        Issue: {
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "blocker";
            /** Message */
            message: string;
            evidence: components["schemas"]["Evidence"];
        };
        /** KnowledgeGraph */
        KnowledgeGraph: {
            project: components["schemas"]["Project"];
            /** Files */
            files?: components["schemas"]["FileNode"][];
            /** Components */
            components?: components["schemas"]["Component"][];
            /** Hooks */
            hooks?: components["schemas"]["Hook"][];
            /** Routes */
            routes?: components["schemas"]["Route"][];
            stateManagement: components["schemas"]["StateManagement"];
            apiLayer?: components["schemas"]["ApiLayer"];
            /** Assets */
            assets?: components["schemas"]["Asset"][];
            /** Edges */
            edges?: components["schemas"]["Edge"][];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * LayoutHint
         * @description Flex/grid layout info for one element.
         */
        LayoutHint: {
            /** Elementtag */
            elementTag: string;
            /** Hasflexclass */
            hasFlexClass: boolean;
            /** Flexdirection */
            flexDirection?: ("row" | "column") | null;
            /** Isgrid */
            isGrid: boolean;
        };
        /** LibraryFinding */
        LibraryFinding: {
            /** Name */
            name: string;
            /** Version */
            version?: string | null;
            /**
             * Category
             * @enum {string}
             */
            category: "routing" | "state" | "http" | "styling" | "animation" | "ui" | "build" | "other";
            /**
             * Status
             * @enum {string}
             */
            status: "compatible" | "needs-conversion" | "partial" | "unsupported" | "unknown";
            /** Compatibility */
            compatibility: number;
            /** Rnequivalents */
            rnEquivalents?: components["schemas"]["RnEquivalent"][];
            /** Notes */
            notes?: string | null;
        };
        /** ManualReviewCandidate */
        ManualReviewCandidate: {
            /** Componentid */
            componentId: string;
            /** Reason */
            reason: string;
        };
        /**
         * MappedDiagnostic
         * @description A diagnostic tied back to the transform that produced it.
         *
         *     This is the exact payload the AI Resolution Engine will receive. A raw
         *     ``tsc`` error is useless to a repair loop unless we know which file, which
         *     transform provenance, and which residue (REJOX-TODO) it belongs to.
         */
        MappedDiagnostic: {
            diagnostic: components["schemas"]["Diagnostic"];
            /** File */
            file?: string | null;
            /** Sourcecomponent */
            sourceComponent?: string | null;
            provenance?: components["schemas"]["ConfidenceSource"] | null;
            /** Nearbytodo */
            nearbyTodo?: string[];
            /** Sourcesnippet */
            sourceSnippet?: string | null;
            /** Originalsnippet */
            originalSnippet?: string | null;
            residue?: components["schemas"]["UnhandledItem"] | null;
        };
        /**
         * MigrateRequest
         * @description Request body for the migrate endpoint (a :class:`SourceRequest` + options).
         */
        MigrateRequest: {
            /**
             * Path
             * @description Local path to a React project root.
             */
            path?: string | null;
            /**
             * Runid
             * @description A run id from a prior /api/upload.
             */
            runId?: string | null;
            /**
             * Root
             * @description Candidate root (relative) to use.
             */
            root?: string | null;
            /**
             * Answers
             * @description Ask-stage answers, e.g. {'styling-engine': 'nativewind'}.
             */
            answers?: {
                [key: string]: string;
            };
            /**
             * Outdir
             * @description Where to emit (local-path mode only); the run's output/ dir for a runId.
             */
            outDir?: string | null;
            /**
             * Install
             * @description Run npm install (cached across runs).
             * @default true
             */
            install: boolean;
            /**
             * Runbundle
             * @description Run the Metro bundle (slowest stage).
             * @default true
             */
            runBundle: boolean;
        };
        /** MigrateResponse */
        MigrateResponse: {
            report: components["schemas"]["AnalysisReport"];
            plan: components["schemas"]["MigrationPlan"];
            emission: components["schemas"]["EmittedProject"];
            validation: components["schemas"]["ValidationResult"];
            /** Mappeddiagnostics */
            mappedDiagnostics?: components["schemas"]["MappedDiagnostic"][];
            validatedScores?: components["schemas"]["ValidatedScores"] | null;
            /** Runid */
            runId?: string | null;
        };
        /** MigrationPlan */
        MigrationPlan: {
            /** Projectname */
            projectName: string;
            /** Questions */
            questions?: components["schemas"]["Question"][];
            /** Steps */
            steps?: components["schemas"]["PlanStep"][];
            /** Manualreviewcandidates */
            manualReviewCandidates?: components["schemas"]["ManualReviewCandidate"][];
            /** Unsupporteditems */
            unsupportedItems?: components["schemas"]["UnsupportedItem"][];
        };
        /**
         * PlanResponse
         * @description Combined payload for the API — the frontend needs both together.
         */
        PlanResponse: {
            report: components["schemas"]["AnalysisReport"];
            plan: components["schemas"]["MigrationPlan"];
        };
        /** PlanStep */
        PlanStep: {
            /** Id */
            id: string;
            /** Order */
            order: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "setup" | "routing" | "components" | "styling" | "state" | "api" | "assets" | "navigation" | "validation";
            /** Targets */
            targets?: string[];
            /**
             * Estimatedeffort
             * @enum {string}
             */
            estimatedEffort: "small" | "medium" | "large";
            /** Dependson */
            dependsOn?: string[];
            /** Affectedbyquestions */
            affectedByQuestions?: string[];
            /** Notes */
            notes?: string | null;
        };
        /** Project */
        Project: {
            /** Name */
            name: string;
            /** Root */
            root: string;
            /**
             * Framework
             * @constant
             */
            framework: "react";
            /**
             * Language
             * @enum {string}
             */
            language: "ts" | "js" | "mixed";
            /** Bundler */
            bundler?: string | null;
            /** Dependencies */
            dependencies?: {
                [key: string]: string;
            };
        };
        /** PropInfo */
        PropInfo: {
            /** Name */
            name: string;
            /** Type */
            type?: string | null;
            /**
             * Optional
             * @default false
             */
            optional: boolean;
        };
        /** Question */
        Question: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Context */
            context: string;
            /** Options */
            options?: components["schemas"]["QuestionOption"][];
            /**
             * Required
             * @default true
             */
            required: boolean;
            dependsOn?: components["schemas"]["QuestionDependency"] | null;
        };
        /**
         * QuestionDependency
         * @description This question only matters once `optionId` is chosen for `questionId`.
         */
        QuestionDependency: {
            /** Questionid */
            questionId: string;
            /** Optionid */
            optionId: string;
        };
        /** QuestionOption */
        QuestionOption: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Tradeoffs */
            tradeoffs: string;
            /**
             * Isrecommended
             * @default false
             */
            isRecommended: boolean;
        };
        /** RnEquivalent */
        RnEquivalent: {
            /** Name */
            name: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Route */
        Route: {
            /** Path */
            path?: string | null;
            /** Componentname */
            componentName?: string | null;
            /** File */
            file?: string | null;
            /**
             * Hasparams
             * @default false
             */
            hasParams: boolean;
            /** Params */
            params?: string[];
        };
        /**
         * RouteMapping
         * @description A proposed React Navigation screen for a react-router route.
         */
        RouteMapping: {
            /** Screenname */
            screenName: string;
            /** Componentname */
            componentName?: string | null;
            /** Path */
            path?: string | null;
            /** Params */
            params?: string[];
            /**
             * Hasparams
             * @default false
             */
            hasParams: boolean;
        };
        /** RoutingReport */
        RoutingReport: {
            /** Library */
            library?: string | null;
            /** Routes */
            routes?: components["schemas"]["RouteMapping"][];
            /**
             * Hasparams
             * @default false
             */
            hasParams: boolean;
            /** Warnings */
            warnings?: components["schemas"]["Issue"][];
        };
        /**
         * ScoreContribution
         * @description One explainable, signed step of the Coverage figure.
         *
         *     The contract: ``sum(c.delta for c in contributions) == coverage`` (base 0;
         *     positive rows grant an area's budget, negative rows subtract deductions).
         */
        ScoreContribution: {
            /** Label */
            label: string;
            /** Delta */
            delta: number;
            /** Reason */
            reason: string;
            /** Evidence */
            evidence: string;
        };
        /**
         * SkippedFile
         * @description A source file deliberately not emitted, with the reason why.
         */
        SkippedFile: {
            /** Path */
            path: string;
            /** Reason */
            reason: string;
        };
        /**
         * SourceRequest
         * @description A source project — either a landed upload (``runId``) or a local ``path``.
         *
         *     ``root`` optionally selects one of the ingest's ``candidateRoots`` (a
         *     monorepo subdirectory, relative to the run's ``source/``); without it the
         *     detected root is used.
         */
        SourceRequest: {
            /**
             * Path
             * @description Local path to a React project root.
             */
            path?: string | null;
            /**
             * Runid
             * @description A run id from a prior /api/upload.
             */
            runId?: string | null;
            /**
             * Root
             * @description Candidate root (relative) to use.
             */
            root?: string | null;
        };
        /**
         * StageResult
         * @description The outcome of one validation stage (typecheck / bundle / lint).
         */
        StageResult: {
            /**
             * Ran
             * @default false
             */
            ran: boolean;
            /**
             * Passed
             * @default false
             */
            passed: boolean;
            /** Diagnostics */
            diagnostics?: components["schemas"]["Diagnostic"][];
            /**
             * Errorcount
             * @default 0
             */
            errorCount: number;
            /** Skippedreason */
            skippedReason?: string | null;
            /** Rawtail */
            rawTail?: string | null;
        };
        /** StateManagement */
        StateManagement: {
            /**
             * Library
             * @enum {string}
             */
            library: "zustand" | "context" | "none";
            /** Stores */
            stores?: components["schemas"]["Store"][];
        };
        /** Store */
        Store: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** File */
            file: string;
            /** Statekeys */
            stateKeys?: string[];
            /** Usedby */
            usedBy?: string[];
        };
        /** StylingReport */
        StylingReport: {
            /** Approaches */
            approaches?: string[];
            /**
             * Tailwindclasscount
             * @default 0
             */
            tailwindClassCount: number;
            /** Unmappableclasses */
            unmappableClasses?: string[];
            /**
             * Cssmodulecount
             * @default 0
             */
            cssModuleCount: number;
        };
        /** Summary */
        Summary: {
            /** Componentcount */
            componentCount: number;
            /** Pagecount */
            pageCount: number;
            /** Routecount */
            routeCount: number;
            /** Apiendpointcount */
            apiEndpointCount: number;
            /** Storecount */
            storeCount: number;
        };
        /**
         * TextNodeInfo
         * @description A raw text / expression child in JSX.
         */
        TextNodeInfo: {
            /** Jsxparenttag */
            jsxParentTag: string;
            /** Text */
            text: string;
            /** Isbare */
            isBare: boolean;
        };
        /** TransformWarning */
        TransformWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Line */
            line: number;
        };
        /**
         * UnhandledItem
         * @description Something rules could not safely resolve → AI Resolution Engine residue.
         */
        UnhandledItem: {
            /** Code */
            code: string;
            /** Snippet */
            snippet: string;
        };
        /** UnsupportedItem */
        UnsupportedItem: {
            /** Name */
            name: string;
            /** Reason */
            reason: string;
            /** Suggestion */
            suggestion: string;
        };
        /**
         * ValidatedScores
         * @description Coverage / Confidence recomputed from the EMITTED + VALIDATED project,
         *     not from the Analyzer's static-analysis prediction.
         *
         *     Confidence is provenance-driven, exactly as the Analyzer defines it, but now
         *     keyed to what actually happened: a file is worth 100 when it was produced
         *     deterministically and the validator passed on it, 80 when it carried a
         *     deterministic warning, and is EXCLUDED (residue) when it still has an
         *     unresolved REJOX-TODO — that file counts against Coverage instead.
         */
        ValidatedScores: {
            /** Coverage */
            coverage: number;
            /** Confidence */
            confidence: number;
            /** Workingcoverage */
            workingCoverage: number;
            /**
             * Workingfilecount
             * @default 0
             */
            workingFileCount: number;
            /** Migratedfilecount */
            migratedFileCount: number;
            /** Residuefilecount */
            residueFileCount: number;
            /** Totalunitcount */
            totalUnitCount: number;
            /** Validatorpassed */
            validatorPassed: boolean;
            /**
             * Cleandeterministic
             * @default 0
             */
            cleanDeterministic: number;
            /**
             * Cleanwithwarning
             * @default 0
             */
            cleanWithWarning: number;
            /** Failedunits */
            failedUnits?: string[];
            /** Predictedcoverage */
            predictedCoverage?: number | null;
            /** Predictedconfidence */
            predictedConfidence?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationResult
         * @description The full verdict on an emitted project.
         */
        ValidationResult: {
            /**
             * Passed
             * @default false
             */
            passed: boolean;
            /**
             * Installed
             * @default false
             */
            installed: boolean;
            typecheck: components["schemas"]["StageResult"];
            bundle: components["schemas"]["StageResult"];
            lint?: components["schemas"]["StageResult"] | null;
            /**
             * Durationseconds
             * @default 0
             */
            durationSeconds: number;
            /** Toolversions */
            toolVersions?: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    upload_api_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestedProject"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_github_api_upload_github_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GithubUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestedProject"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_api_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    migrate_api_migrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MigrateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_runs__run_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
