/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ShowcaseData {
  graph: ShowcaseGraph
  meta: ShowcaseMeta
  project: ShowcaseProject
  question: ShowcaseQuestion
  results: ShowcaseResults
  waves?: ShowcaseWaveStep[]
}
export interface ShowcaseGraph {
  edges?: ShowcaseEdge[]
  nodes?: ShowcaseNode[]
}
export interface ShowcaseEdge {
  from: string
  kind: string
  to: string
}
export interface ShowcaseNode {
  id: string
  kind: string
  label: string
  sourceFile: string
}
/**
 * Provenance of the run — enough to reproduce it byte-for-byte.
 *
 * ``generatedAt`` is intentionally NOT wall-clock: it is the commit date of the
 * benchmarked ``sample-app`` subtree (or ``SOURCE_DATE_EPOCH`` when set), so two
 * exports of the same inputs are byte-identical.
 */
export interface ShowcaseMeta {
  aiProvider: string
  generatedAt: string
  rejoxVersion: string
  reproduce: string
  sampleProject: string
  schemaVersion?: number
  sourceCommit?: string | null
}
export interface ShowcaseProject {
  counts: ShowcaseCounts
  name: string
  sourceFiles?: string[]
  stylingApproaches?: string[]
}
export interface ShowcaseCounts {
  apiEndpoints: number
  components: number
  pages: number
  routes: number
  stores: number
}
export interface ShowcaseQuestion {
  context: string
  evidence: ShowcaseQuestionEvidence
  id: string
  options?: ShowcaseQuestionOption[]
  recommended?: string | null
  title: string
}
/**
 * The genuine justification behind the navigator-shape question.
 *
 * This question is an AI *proposal*, not a formal analyzer finding, so there is
 * no ``Issue``/``Evidence`` object behind it. What DID justify it is captured
 * here verbatim: the AI's proposed shape + rationale, and the source nav UI
 * summary (the only thing the LLM saw) that the proposal reasoned over.
 */
export interface ShowcaseQuestionEvidence {
  fellBack: boolean
  navComponent: string
  proposedShape: string
  rationale: string
  topLevelLinks?: string[]
}
export interface ShowcaseQuestionOption {
  id: string
  isRecommended: boolean
  label: string
}
export interface ShowcaseResults {
  contributions?: ShowcaseContribution[]
  llmCalls: number
  llmCallsByPhase?: PhaseLlmCount[]
  metroPassed: boolean
  metroRan: boolean
  predictedConfidence: number
  predictedCoverage: number
  repairRounds: number
  tscErrorCount: number
  tscPassed: boolean
  validatedCompilingCoverage?: number | null
  validatedConfidence?: number | null
  validatedStrictCoverage?: number | null
}
export interface ShowcaseContribution {
  delta: number
  evidence: string
  label: string
  reason: string
}
/**
 * LLM calls attributed to one pipeline phase.
 *
 * ``calls`` is a MEASURED delta of the run's own call counter across the phase's
 * boundary — never derived, assumed, or written as a literal (including the
 * zeros). A phase whose count cannot be observed is omitted from the list, not
 * reported as zero.
 */
export interface PhaseLlmCount {
  calls: number
  phase: string
}
/**
 * One plan step, carrying the engine's OWN ``wave`` field (not a
 * recomputation) plus title, kind and targets.
 */
export interface ShowcaseWaveStep {
  kind: string
  order: number
  targets?: string[]
  title: string
  wave: number
}
